stages:
  - verify
  - build
  - test

build:
  stage: build
  only:
    - main
  image: "gitlab.lrz.de:5005/acn/terms/2022ws/container/debian_bullseye:latest"
  script:
    - cd quic-project/implementation
    - ./build.sh
    - mv artifact.zip $CI_PROJECT_DIR
  artifacts:
    paths:
      - artifact.zip

build_pandoc:
  stage: build
  only:
    - main
  image: "gitlab.lrz.de:5005/acn/terms/2022ws/container/latex:latest"
  script:
    - cd quic-project/quic-project4
    - make
    - mv Problem4.pdf $CI_PROJECT_DIR
  artifacts:
    paths:
      - Problem4.pdf

run_test:
  stage: test
  only:
    - main
  image: "gitlab.lrz.de:5005/acn/terms/2022ws/container/interop_runner:latest"
  needs:
    - job: build
      artifacts: true
  script:
    - unzip artifact.zip -d /tmp
    - cd /quic-interop-runner 
    - (python3 run.py -t handshake,transfer,multihandshake,versionnegotiation,chacha20,resumption,retry,zerortt,transportparameter || true)
    - mv /quic-interop-runner/logs* $CI_PROJECT_DIR
  artifacts:
    paths:
      - "logs*/"
    when: always


run_measurement:
  stage: test
  only:
    - main
  image: "gitlab.lrz.de:5005/acn/terms/2022ws/container/interop_runner:latest"
  needs:
    - job: build
      artifacts: true
  script:
    - unzip artifact.zip -d /tmp
    - cd /quic-interop-runner
    - (python3 run.py -t goodput,optimize || true)
    - mv /quic-interop-runner/logs* $CI_PROJECT_DIR
  when: manual
  artifacts:
    paths:
      - "logs*/"
    when: always

